// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxSa2XnjjpLTIrm9p17mVAjW-8IlkgjA',
    appId: '1:907200658808:web:23541cedfc099871aedc8d',
    messagingSenderId: '907200658808',
    projectId: 'local-bee',
    authDomain: 'local-bee.firebaseapp.com',
    storageBucket: 'local-bee.appspot.com',
    measurementId: 'G-X071KKM76F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjIfZ7XGstOEmplYO1ZC1-2LZxc5LTBiM',
    appId: '1:907200658808:android:600adecc17ead339aedc8d',
    messagingSenderId: '907200658808',
    projectId: 'local-bee',
    storageBucket: 'local-bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOYPtf4ZSHnPmS7q-dW_e8c20RiOwk7OU',
    appId: '1:907200658808:ios:721e88fb00d5a3d4aedc8d',
    messagingSenderId: '907200658808',
    projectId: 'local-bee',
    storageBucket: 'local-bee.appspot.com',
    iosBundleId: 'com.example.localBee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOYPtf4ZSHnPmS7q-dW_e8c20RiOwk7OU',
    appId: '1:907200658808:ios:ee541665f0125569aedc8d',
    messagingSenderId: '907200658808',
    projectId: 'local-bee',
    storageBucket: 'local-bee.appspot.com',
    iosBundleId: 'com.example.localBee.RunnerTests',
  );
}
